#List of curio slot type settings
[[curiosSettings]]
identifier = "ring"
size = 5
[[curiosSettings]]
identifier= "charm"
size = 3
[[curiosSettings]]
identifier= "necklace"
size = 3
[[curiosSettings]]
identifier= "belt"
size = 2
[[curiosSettings]]
identifier= "body"
size = 2
