
#Stops the listed entities from being used in the Well of Suffering.
#Use the registry name of the entity. Vanilla entities do not require the modid.
[Blacklist]
	wellOfSuffering = ["dummmmmmy:target_dummy", "ars_nouveau:wilden_boss", "botania:doppleganger", "createaddition:overcharged_hammer", "create:super_glue", "create:stationary_contraption", "create:seat", "create:potato_projectile", "create:gantry_contraption", "create:crafting_blueprint", "create:contraption", "clumps:xp_orb_big", "cofh_core:knife", "dummmmmmy:dummy_number", "hats:hat", "sons_of_sins:wistiver", "sons_of_sins:walking_bed", "sons_of_sins:prowler", "sons_of_sins:iron_oven", "sons_of_sins:iron_hit", "sons_of_sins:entitybulletbloody_projectile", "sons_of_sins:curse", "sons_of_sins:bloody_driver", "sons_of_sins:bloody_butcher"]

#Amount of LP the Sacrificial Dagger should provide for each damage dealt.
["Config Values"]
	#Range: 0 ~ 10000
	sacrificialDaggerConversion = 100
	#Declares the amount of LP gained per HP sacrificed for the given entity.
	#Setting the value to 0 will blacklist it.
	#Use the registry name of the entity followed by a ';' and then the value you want.
	#Vanilla entities do not require the modid.
	sacrificialValues = ["villager;100", "slime;15", "enderman;10", "cow;100", "chicken;100", "horse;100", "sheep;100", "wolf;100", "ocelot;100", "pig;100", "rabbit;100", "dummmmmmy:target_dummy;0", "botania:doppleganger;0", "ars_nouveau:wilden_boss;0", "occultism:afrit_wild;0", "occultism:possessed_enderman;250", "occultism:possessed_endermite;250", "occultism:possessed_ghast;250", "occultism:possessed_skeleton;250", "occultism:wild_hunt_skeleton;250", "occultism:wild_hunt_wither_skeleton;250", "whisperwoods:hidebehind;500", "whisperwoods:hirschgeist;500", "whisperwoods:zotzpyre;500", "sons_of_sins:wistiver;0", "sons_of_sins:walking_bed;0", "sons_of_sins:prowler;0", "sons_of_sins:iron_oven;0", "sons_of_sins:iron_hit;0", "sons_of_sins:entitybulletbloody_projectile;0", "sons_of_sins:curse;0", "sons_of_sins:bloody_driver;0", "sons_of_sins:bloody_butcher;0"]
	#State that the dungeon spawning ritual can only be activated when using a Creative Activation Crystal.
	#Used on servers for if you do not trust your players to not destroy other people's bases.
	makeDungeonRitualCreativeOnly = false

