
[general]
	#Colors must be specified in #RRGGBB format
	"color values" = ["#FFFFFF", "#00FFFF", "#A400C3", "#E40779", "#00FF00", "#7F00FF"]
	#Always show armor bar even if empty?
	"Always show bar" = false
	#Show empty armor icons?
	"Show empty icons" = false

