import mods.botania.Orechid;
import crafttweaker.api.item.MCWeightedItemStack;
import crafttweaker.api.tag.MCTag;

craftingTable.addShapeless("marble1", <item:quark:marble>, [<item:chisel:marble/raw>]);
craftingTable.addShapeless("marble2", <item:chisel:marble/raw>, [<item:astralsorcery:marble_raw>]);
craftingTable.addShapeless("marble3", <item:astralsorcery:marble_raw>, [<item:quark:marble>]);
craftingTable.addShapeless("dry_grass", <item:botania:dry_grass>, [<item:minecraft:dirt>, <item:botania:dry_seeds>]);
craftingTable.addShapeless("golden_grass", <item:botania:golden_grass>, [<item:minecraft:dirt>, <item:botania:golden_seeds>]);
craftingTable.addShapeless("vivid_grass", <item:botania:vivid_grass>, [<item:minecraft:dirt>, <item:botania:vivid_seeds>]);
craftingTable.addShapeless("scorched_grass", <item:botania:scorched_grass>, [<item:minecraft:dirt>, <item:botania:scorched_seeds>]);
craftingTable.addShapeless("infused_grass", <item:botania:infused_grass>, [<item:minecraft:dirt>, <item:botania:infused_seeds>]);
craftingTable.addShapeless("mutated_grass", <item:botania:mutated_grass>, [<item:minecraft:dirt>, <item:botania:mutated_seeds>]);
craftingTable.addShapeless("enchanted_soil", <item:botania:enchanted_soil>, [<item:minecraft:dirt>, <item:botania:overgrowth_seed>]);
//craftingTable.addShapeless("farmland", <item:minecraft:farmland>, [<item:minecraft:dirt>]);
craftingTable.addShapeless("fertilized_farmland", <item:farmingforblockheads:fertilized_farmland_healthy>, [<item:minecraft:farmland>, <item:farmingforblockheads:red_fertilizer>]);
//craftingTable.addShapeless("rich_farmland", <item:farmersdelight:rich_soil_farmland>, [<item:farmersdelight:rich_soil>]);
craftingTable.removeByName("eidolon:candle");
craftingTable.addShaped("eidolon_candle", <item:eidolon:candle> * 4, [[<tag:items:forge:tallow>], [<tag:items:supplementaries:candle/wick>]]);
craftingTable.addShaped("chest", <item:minecraft:chest>, [[<tag:items:minecraft:planks>, <tag:items:minecraft:planks>, <tag:items:minecraft:planks>], [<tag:items:minecraft:planks>, <item:minecraft:air>, <tag:items:minecraft:planks>], [<tag:items:minecraft:planks>, <tag:items:minecraft:planks>, <tag:items:minecraft:planks>]]);
craftingTable.removeByName("createdeco:netherite_bars");
craftingTable.addShaped("netherite_bars", <item:createdeco:netherite_bars>*64, [[<tag:items:forge:ingots/netherite>, <tag:items:forge:ingots/netherite>], [<tag:items:forge:ingots/netherite>, <tag:items:forge:ingots/netherite>]]);
craftingTable.removeByName("createdeco:netherite_catwalk");
craftingTable.addShaped("netherite_catwalk", <item:createdeco:netherite_catwalk>*64, [[<item:minecraft:air>, <tag:items:forge:plates/netherite>, <item:minecraft:air>], [<tag:items:forge:plates/netherite>, <item:createdeco:netherite_bars>, <tag:items:forge:plates/netherite>], [<item:minecraft:air>, <tag:items:forge:plates/netherite>, <item:minecraft:air>]]);
craftingTable.removeByName("createdeco:netherite_mesh_fence");
craftingTable.addShaped("netherite_mesh_fence", <item:createdeco:netherite_mesh_fence>*64, [[<tag:items:forge:plates/netherite>, <tag:items:forge:string>, <tag:items:forge:plates/netherite>], [<tag:items:forge:plates/netherite>, <tag:items:forge:string>, <tag:items:forge:plates/netherite>]]);
stoneCutter.removeByName("createdeco:netherite_sheet_metal_from_netherite_block_stonecutting");
stoneCutter.addRecipe("netherite_sheet_metal_from_netherite_block_stonecutting", <item:createdeco:netherite_sheet_metal> * 64, <item:minecraft:netherite_block>);
furnace.removeByName("quark:tweaks/smelting/bone_meal_utility");
//craftingTable.removeByName("buzzier_bees:candles/candle");
craftingTable.addShaped("quark_candle", <item:quark:white_candle> * 2, [[<tag:items:supplementaries:candle/wick>], [<tag:items:forge:tallow>], [<tag:items:forge:tallow>]]);
craftingTable.removeByName("occultism:crafting/candle");
craftingTable.addShaped("occultism_candle", <item:occultism:candle_white>, [[<tag:items:supplementaries:candle/wick>], [<tag:items:forge:tallow>]]);
craftingTable.addShapeless("quark_candle_white", <item:quark:white_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/white>]);
craftingTable.addShapeless("quark_candle_orange", <item:quark:orange_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/orange>]);
craftingTable.addShapeless("quark_candle_magenta", <item:quark:magenta_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/magenta>]);
craftingTable.addShapeless("quark_candle_light_blue", <item:quark:light_blue_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/light_blue>]);
craftingTable.addShapeless("quark_candle_yellow", <item:quark:yellow_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/yellow>]);
craftingTable.addShapeless("quark_candle_lime", <item:quark:lime_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/lime>]);
craftingTable.addShapeless("quark_candle_pink", <item:quark:pink_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/pink>]);
craftingTable.addShapeless("quark_candle_gray", <item:quark:gray_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/gray>]);
craftingTable.addShapeless("quark_candle_light_gray", <item:quark:light_gray_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/light_gray>]);
craftingTable.addShapeless("quark_candle_cyan", <item:quark:cyan_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/cyan>]);
craftingTable.addShapeless("quark_candle_purple", <item:quark:purple_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/purple>]);
craftingTable.addShapeless("quark_candle_blue", <item:quark:blue_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/blue>]);
craftingTable.addShapeless("quark_candle_brown", <item:quark:brown_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/brown>]);
craftingTable.addShapeless("quark_candle_green", <item:quark:green_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/green>]);
craftingTable.addShapeless("quark_candle_red", <item:quark:red_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/red>]);
craftingTable.addShapeless("quark_candle_black", <item:quark:black_candle>, [<tag:items:quark:candles>, <tag:items:forge:dyes/black>]);
craftingTable.removeByName("minecraft:beehive");
craftingTable.addShaped("beehive", <item:minecraft:beehive>, [[<tag:items:minecraft:planks>, <tag:items:minecraft:planks>, <tag:items:minecraft:planks>], [<item:minecraft:honeycomb>, <item:minecraft:honeycomb>, <item:minecraft:honeycomb>], [<tag:items:minecraft:planks>, <tag:items:minecraft:planks>, <tag:items:minecraft:planks>]]);
craftingTable.addShapeless("normal_to_matrix", <item:quark:matrix_enchanter>, [<item:minecraft:enchanting_table>]);
craftingTable.addShapeless("matrix_to_normal", <item:minecraft:enchanting_table>, [<item:quark:matrix_enchanter>]);
//Orechid Recipies
Orechid.main.registerOreWeight(<block:mana-and-artifice:vinteum_ore>, 7685);
Orechid.main.registerOreWeight(<block:druidcraft:rockroot_ore>, 883);
Orechid.main.registerOreWeight(<block:astralsorcery:rock_crystal_ore>, 883);
Orechid.main.registerOreWeight(<block:druidcraft:fiery_glass_ore>, 2647);
Orechid.main.registerOreWeight(<block:ars_nouveau:arcane_ore>, 2647);
Orechid.main.removeOreWeight(<blockstate:minecraft:coal_ore>);
Orechid.main.removeOreWeight(<blockstate:create:zinc_ore>);
Orechid.main.removeOreWeight(<blockstate:minecraft:iron_ore>);
Orechid.main.registerOreWeight(<block:minecraft:coal_ore>, 29371);
Orechid.main.registerOreWeight(<tag:blocks:forge:ores/zinc>, 2647);
Orechid.main.registerOreWeight(<tag:blocks:forge:ores/iron>, 14685);
Orechid.main.registerOreWeight(<block:druidcraft:moonstone_ore>, 883);
Orechid.main.registerOreWeight(<block:feywild:fey_gem_block>, 2647);
Orechid.nether.registerOreWeight(<block:occultism:iesnium_ore>, 356);
//BLOOD MAGIC
<recipetype:bloodmagic:arc>.addRecipe("black_dye_to_ink", <item:minecraft:ink_sac>, <fluid:minecraft:empty>, <tag:items:forge:dyes/black>, <fluid:minecraft:water> * 250, <tag:items:bloodmagic:arc/reverter>, false, [<item:minecraft:ink_sac> % 25, <item:minecraft:ink_sac> % 12, <item:minecraft:ink_sac> % 6]);
<recipetype:bloodmagic:soulforge>.addRecipe("crystalline_resonator", <item:bloodmagic:crystalline_resonator>, [<item:bloodmagic:weakbloodshard>, <item:bloodmagic:infusedslate>, <tag:items:bloodmagic:crystals/demon/split>, <tag:items:forge:ingots>], 2048, 500);
<recipetype:bloodmagic:soulforge>.addRecipe("primitive_explosive_cell", <item:bloodmagic:primitive_explosive_cell>, [<item:minecraft:fire_charge>, <tag:items:forge:dusts/coal>, <tag:items:forge:dusts/saltpeter>, <tag:items:forge:sand>], 128, 10);
//CREATE
<recipetype:create:pressing>.addRecipe("zinc_coin", [<item:createdeco:zinc_coin> % 100], <tag:items:forge:nuggets/zinc>);
<recipetype:create:pressing>.addRecipe("copper_coin", [<item:createdeco:copper_coin> % 100], <tag:items:forge:nuggets/copper>);
<recipetype:create:pressing>.addRecipe("brass_coin", [<item:createdeco:brass_coin> % 100], <tag:items:forge:nuggets/brass>);
<recipetype:create:pressing>.addRecipe("iron_coin", [<item:createdeco:iron_coin> % 100], <tag:items:forge:nuggets/iron>);
<recipetype:create:pressing>.addRecipe("gold_coin", [<item:createdeco:gold_coin> % 100], <tag:items:forge:nuggets/gold>);
<recipetype:create:pressing>.addRecipe("netherite_coin", [<item:createdeco:netherite_coin> % 100], <tag:items:forge:nuggets/netherite>);
<recipetype:create:mixing>.addRecipe("farmland", "none", <item:minecraft:farmland>, [<item:minecraft:dirt>], [<fluid:minecraft:water>*250]);
<recipetype:create:mixing>.addRecipe("rich_farmland", "none", <item:farmersdelight:rich_soil_farmland>, [<item:farmersdelight:rich_soil>], [<fluid:minecraft:water>*250]);
<recipetype:create:mixing>.addRecipe("deepfarmland", "none", <item:undergarden:deepsoil_farmland>, [<item:undergarden:deepsoil>], [<fluid:minecraft:water>*250]);
//AS > ARC
<recipetype:bloodmagic:arc>.addRecipe("aqua_to_resonating_gem", <item:astralsorcery:resonating_gem>, <fluid:minecraft:empty>, <tag:items:forge:gems/aquamarine>, <fluid:astralsorcery:liquid_starlight> * 275, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("redstone_to_gunpowder", <item:minecraft:gunpowder>, <fluid:minecraft:empty>, <tag:items:forge:dusts/redstone>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("gunpowder_to_glowstone", <item:minecraft:glowstone_dust>, <fluid:minecraft:empty>, <tag:items:forge:gunpowder>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("pearl_to_eye", <item:minecraft:ender_eye>, <fluid:minecraft:empty>, <tag:items:forge:ender_pearls>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("sand_to_clay", <item:minecraft:clay>, <fluid:minecraft:empty>, <tag:items:minecraft:sand>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("slimeball_to_magma_cream", <item:minecraft:magma_cream>, <fluid:minecraft:empty>, <item:minecraft:slime_ball>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("melon_to_glistering", <item:minecraft:glistering_melon_slice>, <fluid:minecraft:empty>, <item:minecraft:melon_slice>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("carrot_to_golden", <item:minecraft:golden_carrot>, <fluid:minecraft:empty>, <tag:items:forge:crops/carrot>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("infused_to_vibrant", <item:astralsorcery:infused_wood_infused>, <fluid:minecraft:empty>, <item:astralsorcery:infused_wood>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("glass_to_lens", <item:astralsorcery:glass_lens>, <fluid:minecraft:empty>, <tag:items:forge:glass_panes>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("glass_to_ice", <item:minecraft:ice>, <fluid:minecraft:empty>, <tag:items:forge:glass>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("dirt_to_grass", <item:minecraft:grass_block>, <fluid:minecraft:empty>, <item:minecraft:dirt>, <fluid:astralsorcery:liquid_starlight> * 100, <item:bloodmagic:crystalline_resonator>.anyDamage(), false, []);
<recipetype:bloodmagic:arc>.addRecipe("slate_ampoule", <item:bloodmagic:slate_ampoule>, <fluid:minecraft:empty>, <tag:items:forge:stone>, <fluid:bloodmagic:life_essence_fluid> * 500, <tag:items:bloodmagic:arc/cuttingfluid>, false);
